version: '2'
networks:
  wapps:
    external: true
services:
  portainer:
    command: "--logo https://raw.githubusercontent.com/MichaelSchmidle/wapps/Kartoffel/wapps-logo.svg"
    image: "portainer/portainer"
    labels:
      - "traefik.http.routers.portainer.entrypoints=https-mgmt"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.tls.certResolver=wapps"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - "wapps"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
      - "./templates.json:/templates.json"
  traefik:
    command:
    - "--api.insecure=true"
    - "--certificatesResolvers.wapps.acme.dnsChallenge.provider=${DNS_PROVIDER}"
    - "--certificatesResolvers.wapps.acme.email=${EMAIL}"
    - "--certificatesResolvers.wapps.acme.storage=/wapps/acme.json"
    - "--entryPoints.http.address=:80"
    - "--entryPoints.https.address=:443"
    - "--entryPoints.https-mgmt.address=:${HTTPS_MGMT_PORT}"
    - "--providers.docker"
    env_file: ".env"
    image: "traefik"
    labels:
      - "traefik.http.routers.traefik.entrypoints=https-mgmt"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.traefik.tls.certResolver=wapps"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - "wapps"
    ports:
      - "${IP}:80:80"
      - "${IP}:443:443"
      - "${IP}:4443:4443"
    restart: "always"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik_acme:/wapps"
volumes:
  portainer_data:
  traefik_acme:
